### ISSUE TITLE
Add `width` and `height` to `inline-id-icon`

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#1165] opened 2022-01-11 16:48 UTC
We can add the `width` and `height` to the `inline-id-icon` css definition in a separate PR since ROR allows 16px height icon. This way, the icon should be consistent across usage like https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/creatibutors.html#L17 . We should also change the `img alt` there too.

_Originally posted by @fenekku in https://github.com/inveniosoftware/react-invenio-deposit/pull/404#discussion_r778850087_

**Comment by lnielsen** [comment] 2022-02-09 08:39
Duplicate of #1161

**Closed by lnielsen** 2022-02-09 08:39 UTC
