### ISSUE TITLE
Subjects facet problems after installing invenio-subjects-mesh

### ISSUE THREAD

**Issue by marijane** [inveniosoftware/invenio-app-rdm#2260] opened 2023-06-15 20:23 UTC
Package version (if known): 9.0

## Describe the bug
After installing invenio-subjects-mesh, any/all subjects appear under the MeSH hierarchy and the system only displays 10 subject facets even when more than 10 terms are in use on records.

## Steps to Reproduce
1. Install invenio-subjects-mesh
2. Create a new record
3. Add some MeSH terms
4. Add some free-text keywords
5. Save the record
6. Browse all records and look at the Subjects facet
7. Notice that the free-text keywords are nested under MeSH and that only 10 subjects facets are listed

## Expected behavior
- Keywords should be in a separate subject facet hierarchy from MeSH, just like how they appear in a separate box on the record display
- All subjects used in the system should be available to use as facets, not just the 10 most used terms

## Screenshots (if applicable)
In these screenshots, the terms called out in red boxes are free-text keywords/not MeSH terms.

<img width="310" alt="image" src="https://github.com/inveniosoftware/invenio-app-rdm/assets/1771847/5eb0e460-c883-4378-a8b4-8704ff88efbe">
<img width="310" alt="image" src="https://github.com/inveniosoftware/invenio-app-rdm/assets/1771847/1d0189e3-0ece-4294-a769-9987116c8065">

## Additional context
I considered filing this in the invenio-subjects-mesh repository but this behavior doesn't seem like it is necessarily specific to the vocabulary, it seems like something about how the system is handling the vocab once installed.

**Comment by fenekku** [comment] 2023-06-18 05:20
Thanks for reporting. This is a duplicate of https://github.com/inveniosoftware/invenio-rdm-records/issues/798 . As there is a number of people interested in this, I will take this on in the coming month. I will still close this ticket and refer to the other one for status. Thanks again!

**Closed by fenekku** 2023-06-18 05:20 UTC
Labels: bug
