### ISSUE TITLE
Previewer caption/title doesn't change when previewing another file

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-app-rdm#642] opened 2021-02-26 10:49 UTC
Package version (if known): 0.20.9

## Describe the bug
The title/caption of the file preview box doesn't change when another file is selected for preview

## Steps to Reproduce
1. Create and publish a new record with files
2. Visit the record's landing page
3. Select a different file for preview
4. See that the previewer's caption is still set to the previous name

## Expected behavior

The previewer's caption/title changes when I preview another file

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/6437519/109290640-29307a80-7828-11eb-8b18-81ea85cfcfc7.png)

![image](https://user-images.githubusercontent.com/6437519/109290714-42392b80-7828-11eb-9a4c-0f4cca5371a3.png)

**Comment by fenekku** [comment] 2021-03-01 21:43
Duplicate of https://github.com/inveniosoftware/invenio-rdm-records/issues/74 which was also reported https://github.com/inveniosoftware/invenio-previewer/issues/110

**Comment by fenekku** [comment] 2021-03-30 13:15
closed by https://github.com/inveniosoftware/invenio-app-rdm/issues/735

**Closed by fenekku** 2021-03-30 13:15 UTC
Labels: bug
