### ISSUE TITLE
ux: language selection dropdown cuts-off text

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-app-rdm#394] opened 2020-11-11 09:06 UTC
![image](https://user-images.githubusercontent.com/1814661/98791638-a1a03680-2405-11eb-9e89-2efbfe3bc373.png)

Not sure if it's some CSS or a different setting for the SUI dropdown

**Comment by lnielsen** [comment] 2020-11-11 09:56
Duplicate of #391

**Closed by lnielsen** 2020-11-11 09:56 UTC
Labels: ux
