### ISSUE TITLE
landing page: show affiliation should not show if there's no affiliations

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#593] opened 2021-02-22 23:35 UTC
Package version (if known): <version>

## Description

1. Submit a record with one or more authors without affiliations.
2. See on the landing page that the "show affiliations" is displayed despite the authors having no affiliations.
3. If you click "show affiliations" in toggles to "hide affiliations" and you can no longer toggle it back.

Expected that "show affiliations" is not displayed at all.

## Screenshots (if applicable)

![Screenshot 2021-02-23 at 00 32 14](https://user-images.githubusercontent.com/1698163/108783913-94e7be80-756e-11eb-8277-5f8ae0fdb08b.png)

**Comment by fenekku** [comment] 2021-02-23 14:32
Duplicate of https://github.com/inveniosoftware/invenio-rdm-records/issues/290 . This other issue applies as well: https://github.com/inveniosoftware/invenio-rdm-records/issues/304

**Closed** 2021-02-25 07:41 UTC
Labels: bug, ux
