### ISSUE TITLE
Can preview link caused an "Internal Server Error"

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#871] opened 2021-06-03 06:35 UTC
Can preview link caused an "Internal Server Error" (after creating and copying link via the button). Record in question is in the CERN sandbox: https://inveniordm.web.cern.ch/records/bvj47-0ty78

**Comment by jrcastro2** [comment] 2021-06-08 12:36
This was fixed in v4.0.0, this is the commit <https://github.com/inveniosoftware/invenio-app-rdm/commit/2e72dbe809b86018ce06185a96bd96f0aa35ecc4>.
Closing issue since not able to reproduce it in QA env.

**Closed by jrcastro2** 2021-06-08 12:36 UTC
Labels: bug, ux
