### ISSUE TITLE
aggregation filters not "multiple choice"

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#96] opened 2020-03-30 12:39 UTC
When selecting several aggregation values, only the last one applies. I think this is due to the HTTP parameter being called the same and being overwritten when received by the react app?

![Screenshot 2020-03-30 at 14 37 39](https://user-images.githubusercontent.com/6756943/77913251-38175180-7294-11ea-8593-76b2894961d5.png)

In the image you can see how two filters are selected, yet only the second one is applied.

**Comment by fenekku** [comment] 2020-09-01 18:06
Related to https://github.com/inveniosoftware/invenio-records-resources/issues/73

**Comment by fenekku** [comment] 2020-09-10 14:19
React-Search-Kit doesn't send a request with the facets repeated. I don't know if this is configuration issue or a bug (https://github.com/inveniosoftware/react-searchkit/issues/105) . Reassigning to someone more familiar with react-search-kit to expedite things.

**Comment by ntarocco** [comment] 2020-09-14 14:29
This is how Invenio works at the moment. When you have normal filters (not `post` filters) configured, then you need to repeat the same filter name with different values.
The python code will split it. See [here](https://github.com/inveniosoftware/invenio-records-rest/blob/3aaa86b1493e0c3010d1cf38d083d92335455f29/invenio_records_rest/facets.py#L88).
See for example: <https://videos.cern.ch/search?page=1&size=21&q=&language=en&language=fr>

**Comment by fenekku** [comment] 2020-09-14 17:09
@ntarocco Yes, I had seen this part of code from Invenio, but the problem seems to be on the frontend. The react-search-kit app on invenio-app-rdm doesn't send the additional `language` querystring. Also we are talking about `post_filters`  here... So we probably misconfigured our react-searck-kit app I am thinking... What do we need to fix?

**Comment by ntarocco** [comment] 2020-09-14 17:32
I think @zzacharo will have a look, otherwise I need more details (expected vs current behaviors with examples) but if in the URLs you see multiple times the same filter with different values, then RSK is doing the right thing.

**Comment by Glignos** [comment] 2020-10-13 15:48
![Screenshot 2020-10-13 at 17 46 18](https://user-images.githubusercontent.com/16304052/95884258-2dc62c00-0d7c-11eb-85d4-e0641dc787f0.png)
![Screenshot 2020-10-13 at 17 46 10](https://user-images.githubusercontent.com/16304052/95884268-30288600-0d7c-11eb-8748-16c8fefb2ba2.png)
This cannot be reproduced currently.

**Comment by fenekku** [comment] 2020-10-13 21:43
This was fixed by https://github.com/inveniosoftware/react-searchkit/commit/db939e9a60e002ac6314a9a387e54e438c0d4804

**Closed by fenekku** 2020-10-13 21:43 UTC
