### ISSUE TITLE
Preview/Download files: 'Could not send file' error in public record

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#747] opened 2021-03-30 10:38 UTC
Package version (if known): <version>

invenio-cli 0.23.0
InvenioRDM v2.0
Instance: https://inveniordm.web.cern.ch/ 2021-03-29

## Describe the bug

- We created records in the [invenioRDM-demo](https://inveniordm.web.cern.ch/) with different accounts (both on firefox) and all of our records with several versions and published them completely public.
- I wasn't able to preview or download the record-files from my workmate. He wasn't able to preview or download the record-files from the record I created. We also checked a record that was created by someone else that we don't know. I was able to download it my workmate wasn't able.
- Later I checked again and tried different browsers (firefox and chromium).
- The error message in chromium was for me 'zipfile is not previewable' and "status 500" "errors: Could not send file: Resource not found: b'/data'".
- In firefox I get a 'broken preview-picture' and the same error message for a png-file.
- Interestingly, files that I cannot see and download in firefox I can in chromium, and the other way round.
- I tried to see the reproduce the same error with different accounts on a local instance, but so far I wasn't able to reproduce it.

My firefox version: 78.8.0esr (64-bit) (debian 10)
My chromium version: Version 88.0.4324.182 (Developer Build) built on Debian 10.8, running on Debian 10.8 (64-bit)

## Steps to Reproduce

Unfortunately, we have no idea what is going on.

## Expected behavior

Public uploaded files can be previewed and downloaded from everybody without error.

## Screenshots (if applicable)

- Record from (for us) unknown person - on the left firefox - on the right chromium
![Screenshot_2021-03-29_13-51-04](https://user-images.githubusercontent.com/74763324/112974871-3d330900-9153-11eb-916f-942bca72a979.png)
- Record from (for us) unknown person - clicking on 'Download'
![Screenshot_2021-03-29_13-51-20](https://user-images.githubusercontent.com/74763324/112975002-6b184d80-9153-11eb-90e3-794caf301722.png)
- Record from my workmate - on the left firefox - on the right chromium
![Screenshot_2021-03-29_13-56-47](https://user-images.githubusercontent.com/74763324/112975168-9f8c0980-9153-11eb-9269-4ee4c9c93a0b.png)
- Record my workmate - clicking on 'Download'
![Screenshot_2021-03-29](https://user-images.githubusercontent.com/74763324/112975370-d530f280-9153-11eb-9cd9-a2a00b244f6d.png)
- Local fresh setup - instance using different accounts.
![unknown](https://user-images.githubusercontent.com/74763324/112975433-ea0d8600-9153-11eb-8721-a616eea868e8.png)

## Uploaded files

My files:
![circle](https://user-images.githubusercontent.com/74763324/112975723-4a042c80-9154-11eb-9f32-5e8ef1ba38ff.png)
![rectangle](https://user-images.githubusercontent.com/74763324/112975726-4a042c80-9154-11eb-9fd1-1d41fef543b5.png)

Workmate files:
![t1_l](https://user-images.githubusercontent.com/74763324/112975798-5d16fc80-9154-11eb-8382-6c0793479971.png)
![t1_s](https://user-images.githubusercontent.com/74763324/112975801-5daf9300-9154-11eb-8bfe-556f11143a48.png)

Files from random record (I never checked what is in there):
[cleaned.zip](https://github.com/inveniosoftware/invenio-app-rdm/files/6228331/cleaned.zip)
[userstudy.zip](https://github.com/inveniosoftware/invenio-app-rdm/files/6228332/userstudy.zip)

**Comment by fenekku** [comment] 2021-04-19 19:08
I can't reproduce this locally with the April release. Here are the steps I followed:

1- Create a public record R1 with green square and circle with user account U1
2- Logout
3- Create a public record R2 with purple rectangles with user account U2
4- Visit R1 and R2 with U2 in Firefox + Chrome (on linux)
5- Download their files
6- Logout
7- Visit R1 and R2 with U1 in Firefox + Chrome (on linux)
8- Download their files


If seems like a problem specific to the demo site's deployment. Letting @lnielsen know and closing this.

**Closed by fenekku** 2021-04-19 19:08 UTC
Labels: bug

**Comment by chriz-uniba** [comment] 2021-04-20 08:48
Yeap, I wasn't able to reproduce it with my own instance neither. @lnielsen asked me on discord to put it here. If anyone ever find out what is/was the issue (even if it is related to the setup of deployment, ...) we would happy to know - so that we do not get into that 'trap' as well when we deploy.
Thanks for taking a look. :)
