### ISSUE TITLE
landing page: multiple citation styles underlined when previously selected, but not anymore

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#943] opened 2021-07-12 08:31 UTC
1. Create a record
2. Publish
3. Click on several citation styles, you will see that the previous ones stay selected (until the focus is out of the browser??)

https://user-images.githubusercontent.com/6756943/125256386-b0c0e680-e2fc-11eb-85e5-7bd7484dfd25.mov

**Comment by zzacharo** [comment] 2021-07-12 14:43
Couldn't reproduce with Chrome/Safari...maybe check again after https://github.com/inveniosoftware/invenio-drafts-resources/pull/154 is merged!

**Comment by ppanero** [comment] 2021-07-12 15:09
Still happening

![image](https://user-images.githubusercontent.com/6756943/125311611-d4535380-e333-11eb-8331-5417b96e2bc3.png)

Lets have a call and fix it :)

**Closed** 2021-07-14 12:32 UTC
