### ISSUE TITLE
record-details: previewer randomly gives error

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#1571] opened 2022-05-13 14:44 UTC
Package version (if known): latest

## Describe the bug
The record details page gives an exception with the below stacktrace
<img width="2295" alt="Screenshot 2022-05-13 at 16 29 10" src="https://user-images.githubusercontent.com/22594783/168308406-d5341519-2e6b-44fd-b621-fa395d9e804e.png">

After refreshing the page it works.

**Comment by ntarocco** [comment] 2022-05-31 07:29
It looks like that it is happening consistently only on a dev env. We have some of these errors in some prod instances, but very few.
It looks like that it is related on how the previewers are registered, but the cause has not been found. Closing the issue for the moment.

**Closed by ntarocco** 2022-05-31 07:29 UTC
Labels: bug
