### ISSUE TITLE
Search: Clear facets on new search term

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-app-rdm#1305] opened 2022-02-25 15:29 UTC
Facets should be cleared from the search query when a search is executed with a new search term, as the facets (including the selected ones) disappear from the ui when there are no results.

**Comment by fenekku** [comment] 2022-02-25 15:36
Is this a duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/1114 ?

**Comment by jennur** [comment] 2022-02-25 15:38
Woops, you're right!

**Closed** 2022-02-25 15:41 UTC
Labels: bug, ux
