### ISSUE TITLE
UI: State of a filter not reset when the filter is not visible anymore

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/invenio-app-rdm#1264] opened 2022-02-15 13:38 UTC
Invenio RDM v7

## Describe the bug
When you are on the search page and enable a filter, then do something that this checkbox vanishes, the state of the checkbox remains enabled.

## Steps to Reproduce
For example, assume there are different filters depending on whether you have "all versions" true or false.

With "allversions = True", I see an `embargoed` checkbox, but with `allversions = False` I don't (because only an old version is embargoed, whatever).

Set `all versions = True` and check the `embargoed` checkbox. Now toggle `all versions` back to `False`.

Now whatever filters you apply, in the backend log, still the query has `...&access_status=embargoed&...` as a parameter, so the filter apparently remains active.

## Expected behavior

Filters that are not visible should also not affect the query.

**Comment by fenekku** [comment] 2022-02-15 15:20
This is essentially a duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/1114. Thanks!

**Closed by fenekku** 2022-02-15 15:20 UTC
Labels: bug
