### ISSUE TITLE
publishing with minimum required fields fails

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#289] opened 2020-10-05 09:20 UTC
Package version (if known): <version>

## Steps to Reproduce
1. Bootstrap an instance
2. Go to uploads
3. Fill in the `*` fields and click `publish`

## Expected behavior

publishing record and redirect to landing page

## Screenshots (if applicable)

![Screenshot 2020-10-05 at 11 18 15](https://user-images.githubusercontent.com/6756943/95062056-b863b700-06fc-11eb-9a0c-376f833fbad4.png)

## Additional context

logs
```
127.0.0.1 - - [05/Oct/2020 11:17:39] "POST /uploads/new HTTP/1.1" 405 -
```

**Comment by fenekku** [comment] 2020-10-05 13:16
I think this is a duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/272 (whether it be creators field or something else at the root cause)

**Comment by ppanero** [comment] 2020-10-05 13:51
I think the main cause was that the route was missing in the view config. But yeah, the bottom nature of both issues might be the same.

**Closed** 2020-10-12 12:10 UTC
Labels: bug
