### ISSUE TITLE
Unclear Validation Error When Featuring Restricted Community

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-app-rdm#2707] opened 2024-06-19 15:36 UTC
Package version (if known): V12 rc2

## Describe the bug
Minor: 
Setting a restricted community as featured results in a generic validation error message instead of an understandable message indicating that the community is not public.

## Steps to Reproduce

1. Go to the administration panel under communities.
2. Attempt to set a restricted community as featured.
3. Observe the validation error message.

## Expected behavior

- An understandable message should be displayed, indicating that the community cannot be featured because it is not public.
- The error should be caught correctly to be shown on the UI side
- It's hard to say whether the community is restricted or not from the administration's view.

## Screenshots (if applicable)
![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/ddf5e840-6711-45b0-94a6-ccd149b0f862)

![image](https://github.com/inveniosoftware/invenio-app-rdm/assets/36583694/4b371dd6-a644-44c6-8735-cc96d2de7655)

## Additional context
The current validation error message is not clear. It should explicitly state that restricted communities cannot be featured.
like its been stated in the logs.
```log
    raise ValidationError(
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/invenio_communities/communities/resources/resource.py", line 207, in featured_create
    item = self.service.featured_create(
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/invenio_records_resources/services/uow.py", line 376, in inner
    res = f(self, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/invenio_communities/communities/services/service.py", line 380, in featured_create
    self.run_components(
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/invenio_records_resources/services/base/service.py", line 72, in run_components
    getattr(component, action)(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.19/envs/test/lib/python3.9/site-packages/invenio_communities/communities/services/components.py", line 140, in featured_create
    raise ValidationError(
marshmallow.exceptions.ValidationError: The community is not public.
127.0.0.1 - - [19/Jun/2024 17:23:54] "POST /api/communities/1a7dfd30-5f7a-47dd-91e1-4aba582f5a68/featured HTTP/1.1" 400 -

```

**Comment by fenekku** [comment] 2024-06-20 13:29
Dupe of: https://github.com/inveniosoftware/invenio-communities/issues/920

Affects version 11 and below too.

**Closed by fenekku** 2024-06-20 13:29 UTC
Labels: bug
