### ISSUE TITLE
deposit: deleting a draft doesn't remove it from the list uploads immediately

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#587] opened 2021-02-22 22:51 UTC
## Steps to Reproduce
1. Go to 'https://127.0.0.1:5000/uploads'
2. Verify that the list of uploads are empty (showing "Get started" text).
2. Click on 'New upload'
3. Click on "Save draft"
4. Click on "Delete"
4. You are redirected back to the list upload page which shows an empty record (No title, no description). 
5. Reload the page. The draft was now removed from the index and the "Get started" page is show again.

## Expected behavior

As an end-user, I expect that something I removed is actually removed, thus when I see the just removed item back on list uploads page I get confused.

The problem is due to the index needing to be updated. 

## Screenshots (if applicable)

![Screenshot 2021-02-22 at 23 49 26](https://user-images.githubusercontent.com/1698163/108780364-9a420a80-7568-11eb-8148-4cdd42089210.png)

**Comment by fenekku** [comment] 2021-02-23 14:22
Isn't this a duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/489 ?

**Comment by zzacharo** [comment] 2021-03-01 09:39
Fixed!

**Closed by zzacharo** 2021-03-01 09:39 UTC
Labels: backend, bug
