### ISSUE TITLE
deposit form: protection widget - files restrictions only visible with uploaded file

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#740] opened 2021-03-28 19:38 UTC
Package version (if known): <version>

## Describe the bug

Protection: The files restriction in the protection widget only become visible after uploading a file. It should be hidden only for metadata-only records.

## Steps to Reproduce

1. Start a new upload.
2. Observe that the protection widget says the records has no files.
3. Now upload a file
2. Observe that the protection widget now allows changing restriction for files.

## Expected behavior

I expect only to see the message about record not having files, when the "metadata only" option is selected.

## Screenshots (if applicable)
![Screenshot 2021-03-28 at 21 29 47](https://user-images.githubusercontent.com/1698163/112765504-ce986300-900d-11eb-96d0-680fe083b201.png)
![Screenshot 2021-03-28 at 21 30 00](https://user-images.githubusercontent.com/1698163/112765505-cf30f980-900d-11eb-9a53-a451515c20bd.png)

**Comment by fenekku** [comment] 2021-03-30 13:26
Duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/585 (I will close the other one, but there is valuable information there to check out)

**Closed** 2021-04-06 13:50 UTC
Labels: bug, known issue, ux
