### ISSUE TITLE
date-type created doesn't accept valid DataCite input

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-app-rdm#1355] opened 2022-03-07 10:16 UTC
Package version (if known): https://inveniordm.web.cern.ch/ (2022-03-07) --- v8 (but also v7).

## Describe the bug

DataCite describes `dateType-created` as
```
The date the resource itself was put
together; this could refer to a timeframe in
ancient history, a date range, or a single date
for a final component, e.g., the finalised file
with all the data.
```
p.46

![image](https://user-images.githubusercontent.com/74763324/157007854-a5c499d8-2b40-4ed7-a50c-e7ba858a9d77.png)
https://doi.org/10.14454/3w3z-sa82
https://schema.datacite.org/meta/kernel-4.4/
https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf

Creating a record-draft does not allow ancient history dates.

## Steps to Reproduce
1. Go to https://inveniordm.web.cern.ch/uploads
    (you are logged in --- having an account)
2. Create a draft with minimal needed fields.
3. Add the following date
![image](https://user-images.githubusercontent.com/74763324/157011566-3f5ce84c-6abd-483f-8874-1926387fbfd0.png)
4. Save draft
5. See error
![image](https://user-images.githubusercontent.com/74763324/157011679-98fd3d43-5754-47a9-997c-40d11e2eadc4.png)

## Expected behavior

Accept valid DataCite dates.

**Comment by lnielsen** [comment] 2022-03-07 16:03
Thanks for reporting. It's a duplicate of https://github.com/inveniosoftware/invenio-rdm-records/issues/197

**Closed by lnielsen** 2022-03-07 16:03 UTC
Labels: bug, backend
