### ISSUE TITLE
Some special characters in community names are not rendered properly on modal

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#2095] opened 2023-02-16 20:47 UTC
Package version (if known): v11

## Describe the bug
Special characters in community names, show up as raw html on the submission modal. Elsewhere they look fine.

Community name: `It's <>!@#$%^&*()_+-[]{}\|~ me`

Renders in the modal as:

![image](https://user-images.githubusercontent.com/1932651/219482647-4242e147-5b77-4292-93a3-5fc977995be0.png)

## Steps to Reproduce
1. Create a community with special characters in its name
2. Fill out the record form to submit to that community
4. Click on "Submit for Review"
6. See error on the modal

## Expected:

Renders as `It's <>!@#$%^&*()_+-[]{}\|~ me` or prevent the special symbols in the community name in the first place.

**Comment by kpsherva** [comment] 2023-02-22 09:10
closing as duplicate, the issue is already solved

**Closed by kpsherva** 2023-02-22 09:10 UTC
Labels: bug

**Comment by fenekku** [comment] 2023-02-22 13:19
Duplicate of and solved where?
