### ISSUE TITLE
bug: clicking on creator names resolves to inaccurate search query

### ISSUE THREAD

**Issue by yashlamba** [inveniosoftware/invenio-app-rdm#2705] opened 2024-06-19 06:45 UTC
## Describe the bug
When clicking a creator name on a record, the search query resolves to -> `/search?q=metadata.creators.person_or_org.name`

## Expected behavior
It should direct to `/search?q=metadata.contributors.person_or_org.name`.

## Additional context
Raised from user support on Zenodo

**Comment by tmorrell** [comment] 2024-06-19 09:35
Duplicate of https://github.com/inveniosoftware/invenio-app-rdm/issues/2247 and it's only wrong for "contributors" (not creators)

**Comment by carlinmack** [comment] 2024-07-15 09:52
Closing in favour of https://github.com/inveniosoftware/invenio-app-rdm/issues/2247

**Closed by carlinmack** 2024-07-15 09:52 UTC
Labels: bug
